-- ============================================================================
-- 河日 Ode Studio — 攝影棚預約系統 Schema
--
-- 資料庫限制（本 schema 已遵守）
--   禁用型別：BIGINT / BIGSERIAL / SMALLINT / UUID / VECTOR / TIME / ENUM
--   可用型別：INTEGER / NUMERIC / VARCHAR / TEXT / DATE / TIMESTAMP /
--            TIMESTAMPTZ / BOOLEAN / JSON / JSONB
--
-- 命名慣例
--   PK           所有主鍵一律 `id INTEGER GENERATED BY DEFAULT AS IDENTITY`
--   FK           `<parent>_id`（外鍵欄位名 = 父表單數 + _id）
--   status 類    一律 VARCHAR + CHECK 約束（不用 ENUM）
--   時段         全部用 start_minute / end_minute（0..1440 分鐘）
--   實際時間     用 TIMESTAMPTZ（例：booking.start_at / end_at）
--   時間戳       created_at / updated_at TIMESTAMPTZ DEFAULT NOW()
--   軟刪除       deleted_at TIMESTAMPTZ（NULL 表示未刪）
--   彈性欄位     metadata JSONB DEFAULT '{}'::jsonb
--
-- CRUD SaaS auto-API 友善設計
--   - 每張表都有單欄位 PK（id）與 created_at / updated_at
--   - 沒有複合主鍵，多對多改為明確 JSONB 或後續加關聯表
--   - 所有 FK 欄位皆建索引，常用查詢欄位（狀態、日期、email）皆建索引
--   - 狀態透過 CHECK 約束限制值域，方便前端 form 選單直接對應
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 註：本 schema 不包含 CREATE FUNCTION / CREATE TRIGGER。
--     updated_at 由應用層（或 SaaS auto-API 平台，如 Directus / NocoDB / Xano
--     / PostgREST 等）於每次 UPDATE 時自動寫入 NOW()。
--     所有表的 updated_at 皆已設 DEFAULT NOW() NOT NULL，INSERT 時無需傳。
-- ----------------------------------------------------------------------------


-- ============================================================================
-- 1. customer_accounts — 前台會員（顧客）
--    - 前台亦允許「訪客預約」（不註冊），該情境下 bookings.customer_account_id = NULL
--    - 已註冊會員：儲存 email/phone/password_hash，可查詢自己的預約歷史
-- ============================================================================
CREATE TABLE customer_accounts (
    id                  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email               VARCHAR(255) NOT NULL,
    phone               VARCHAR(32),
    display_name        VARCHAR(100),
    password_hash       VARCHAR(255),                             -- 允許 NULL：僅第三方登入時
    email_verified_at   TIMESTAMPTZ,
    phone_verified_at   TIMESTAMPTZ,
    marketing_opt_in    BOOLEAN     NOT NULL DEFAULT FALSE,
    last_login_at       TIMESTAMPTZ,
    locale              VARCHAR(16) NOT NULL DEFAULT 'zh-TW',
    metadata            JSONB       NOT NULL DEFAULT '{}'::jsonb,
    is_active           BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at          TIMESTAMPTZ
);
CREATE UNIQUE INDEX idx_customer_accounts_email
    ON customer_accounts (LOWER(email)) WHERE deleted_at IS NULL;
CREATE INDEX idx_customer_accounts_phone
    ON customer_accounts (phone) WHERE deleted_at IS NULL;
CREATE INDEX idx_customer_accounts_active
    ON customer_accounts (is_active) WHERE deleted_at IS NULL;


-- ============================================================================
-- 2. studio_admin_accounts — 後台管理者
--    - role: 'owner' | 'admin' | 'staff'
--    - 純內部帳號，不與 customer_accounts 混用
-- ============================================================================
CREATE TABLE studio_admin_accounts (
    id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email           VARCHAR(255) NOT NULL,
    display_name    VARCHAR(100) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    role            VARCHAR(32)  NOT NULL DEFAULT 'staff',
    last_login_at   TIMESTAMPTZ,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    metadata        JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ,
    CONSTRAINT chk_admin_role CHECK (role IN ('owner', 'admin', 'staff'))
);
CREATE UNIQUE INDEX idx_studio_admin_accounts_email
    ON studio_admin_accounts (LOWER(email)) WHERE deleted_at IS NULL;
CREATE INDEX idx_studio_admin_accounts_active
    ON studio_admin_accounts (is_active) WHERE deleted_at IS NULL;


-- ============================================================================
-- 3. studios — 攝影棚
--    - 一個空間單位。可以有多間（本次 MVP 常見為 1..3 間）
--    - default_hourly_price 為 fallback，實際計費以 pricing_plans 為準
-- ============================================================================
CREATE TABLE studios (
    id                          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    slug                        VARCHAR(64)  NOT NULL,                            -- URL 用短代號
    name                        VARCHAR(120) NOT NULL,
    description                 TEXT,
    address                     VARCHAR(255),
    floor                       VARCHAR(32),                                       -- 樓層資訊
    area_ping                   NUMERIC(6, 2),
    capacity                    INTEGER,                                           -- 最大容納人數
    features                    JSONB        NOT NULL DEFAULT '[]'::jsonb,        -- 設備清單
    default_hourly_price        NUMERIC(10, 2) NOT NULL,
    min_booking_minutes         INTEGER      NOT NULL DEFAULT 60,
    max_booking_minutes         INTEGER      NOT NULL DEFAULT 480,
    booking_increment_minutes   INTEGER      NOT NULL DEFAULT 30,
    advance_booking_days        INTEGER      NOT NULL DEFAULT 90,                 -- 可提前預約天數
    cancellation_hours          INTEGER      NOT NULL DEFAULT 48,                 -- 開始前幾小時可取消
    display_order               INTEGER      NOT NULL DEFAULT 0,
    is_active                   BOOLEAN      NOT NULL DEFAULT TRUE,
    metadata                    JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at                  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at                  TIMESTAMPTZ
);
CREATE UNIQUE INDEX idx_studios_slug
    ON studios (slug) WHERE deleted_at IS NULL;
CREATE INDEX idx_studios_active_order
    ON studios (is_active, display_order) WHERE deleted_at IS NULL;


-- ============================================================================
-- 4. studio_images — 攝影棚的照片
-- ============================================================================
CREATE TABLE studio_images (
    id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    studio_id       INTEGER      NOT NULL REFERENCES studios(id) ON DELETE CASCADE,
    url             VARCHAR(500) NOT NULL,
    alt_text        VARCHAR(255),
    caption         VARCHAR(255),
    display_order   INTEGER      NOT NULL DEFAULT 0,
    is_cover        BOOLEAN      NOT NULL DEFAULT FALSE,
    width           INTEGER,
    height          INTEGER,
    file_size       INTEGER,
    metadata        JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_studio_images_studio
    ON studio_images (studio_id, display_order);
CREATE UNIQUE INDEX idx_studio_images_cover
    ON studio_images (studio_id) WHERE is_cover = TRUE;


-- ============================================================================
-- 5. scenes — 佈景（同一攝影棚內可有多個場景／背景）
-- ============================================================================
CREATE TABLE scenes (
    id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    studio_id       INTEGER      NOT NULL REFERENCES studios(id) ON DELETE CASCADE,
    slug            VARCHAR(64)  NOT NULL,
    name            VARCHAR(120) NOT NULL,
    description     TEXT,
    tags            JSONB        NOT NULL DEFAULT '[]'::jsonb,        -- ['自然光','白色','木質']
    display_order   INTEGER      NOT NULL DEFAULT 0,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    metadata        JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ,
    CONSTRAINT uq_scenes_studio_slug UNIQUE (studio_id, slug)
);
CREATE INDEX idx_scenes_studio
    ON scenes (studio_id, display_order) WHERE deleted_at IS NULL;


-- ============================================================================
-- 6. scene_images — 佈景照片
-- ============================================================================
CREATE TABLE scene_images (
    id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    scene_id        INTEGER      NOT NULL REFERENCES scenes(id) ON DELETE CASCADE,
    url             VARCHAR(500) NOT NULL,
    alt_text        VARCHAR(255),
    caption         VARCHAR(255),
    display_order   INTEGER      NOT NULL DEFAULT 0,
    is_cover        BOOLEAN      NOT NULL DEFAULT FALSE,
    width           INTEGER,
    height          INTEGER,
    file_size       INTEGER,
    metadata        JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_scene_images_scene
    ON scene_images (scene_id, display_order);
CREATE UNIQUE INDEX idx_scene_images_cover
    ON scene_images (scene_id) WHERE is_cover = TRUE;


-- ============================================================================
-- 7. pricing_plans — 定價方案
--    - plan_type: 'hourly'（時計）| 'package'（套裝）| 'flat'（單場固定）
--    - applies_to_weekdays: JSONB array，例：[1,2,3,4,5] 平日、[0,6] 假日
--    - start_minute/end_minute: 適用時段（可用於離峰、深夜方案），NULL 表示全天
--    - priority: 多方案適用時，priority 高者覆蓋低者
-- ============================================================================
CREATE TABLE pricing_plans (
    id                      INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    studio_id               INTEGER        NOT NULL REFERENCES studios(id) ON DELETE CASCADE,
    name                    VARCHAR(100)   NOT NULL,
    plan_type               VARCHAR(32)    NOT NULL DEFAULT 'hourly',
    hourly_price            NUMERIC(10, 2) NOT NULL,
    package_price           NUMERIC(10, 2),                                    -- 套裝總價（若 plan_type=package）
    package_hours           NUMERIC(4, 2),                                     -- 套裝包含小時
    applies_to_weekdays     JSONB          NOT NULL DEFAULT '[0,1,2,3,4,5,6]'::jsonb,
    start_minute            INTEGER,
    end_minute              INTEGER,
    effective_from          DATE,
    effective_to            DATE,
    min_hours               NUMERIC(4, 2)  NOT NULL DEFAULT 1,
    max_hours               NUMERIC(4, 2),
    priority                INTEGER        NOT NULL DEFAULT 0,
    is_active               BOOLEAN        NOT NULL DEFAULT TRUE,
    metadata                JSONB          NOT NULL DEFAULT '{}'::jsonb,
    created_at              TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    deleted_at              TIMESTAMPTZ,
    CONSTRAINT chk_pricing_plan_type
        CHECK (plan_type IN ('hourly', 'package', 'flat')),
    CONSTRAINT chk_pricing_minutes CHECK (
        (start_minute IS NULL AND end_minute IS NULL) OR
        (start_minute >= 0 AND end_minute > start_minute AND end_minute <= 1440)
    ),
    CONSTRAINT chk_pricing_effective CHECK (
        effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from
    )
);
CREATE INDEX idx_pricing_plans_studio_priority
    ON pricing_plans (studio_id, priority DESC)
    WHERE is_active = TRUE AND deleted_at IS NULL;


-- ============================================================================
-- 8. business_hours — 每週固定營業時段
--    - 一個 weekday 可有多列（例：中間午休拆兩段：09:00-14:00 + 15:00-22:00）
--    - is_closed=TRUE 表示該 weekday 公休（start/end 忽略）
-- ============================================================================
CREATE TABLE business_hours (
    id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    studio_id       INTEGER      NOT NULL REFERENCES studios(id) ON DELETE CASCADE,
    weekday         INTEGER      NOT NULL,                            -- 0=Sun .. 6=Sat
    start_minute    INTEGER      NOT NULL,
    end_minute      INTEGER      NOT NULL,
    is_closed       BOOLEAN      NOT NULL DEFAULT FALSE,
    note            VARCHAR(255),
    metadata        JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_business_hours_weekday CHECK (weekday BETWEEN 0 AND 6),
    CONSTRAINT chk_business_hours_minutes CHECK (
        start_minute BETWEEN 0 AND 1440
        AND end_minute BETWEEN 0 AND 1440
        AND end_minute > start_minute
    ),
    CONSTRAINT uq_business_hours UNIQUE (studio_id, weekday, start_minute)
);
CREATE INDEX idx_business_hours_studio
    ON business_hours (studio_id, weekday);


-- ============================================================================
-- 9. time_slots — 時段可用性快取（materialized availability grid）
--    - 由排程任務依 business_hours + pricing_plans + special_dates 預先生成
--    - 月曆 availability 查詢直接查此表，避免多表 JOIN
--    - status: 'available' | 'held' | 'booked' | 'blocked' | 'maintenance' | 'holiday'
--    - booking_id 於 status='booked' 或 'held' 時記錄關聯
--    - held: 顧客加入結帳流程但尚未成立（含 15 分鐘倒數）
-- ============================================================================
CREATE TABLE time_slots (
    id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    studio_id       INTEGER        NOT NULL REFERENCES studios(id) ON DELETE CASCADE,
    slot_date       DATE           NOT NULL,
    start_minute    INTEGER        NOT NULL,
    end_minute      INTEGER        NOT NULL,
    status          VARCHAR(32)    NOT NULL DEFAULT 'available',
    booking_id      INTEGER,                                        -- FK 於 ALTER 補上
    hourly_price    NUMERIC(10, 2),                                 -- 依 pricing_plans 計算後快取
    hold_expires_at TIMESTAMPTZ,                                    -- status='held' 時使用
    block_reason    VARCHAR(255),                                   -- status IN ('blocked','maintenance')
    metadata        JSONB          NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_time_slots_minutes CHECK (
        start_minute BETWEEN 0 AND 1440
        AND end_minute BETWEEN 0 AND 1440
        AND end_minute > start_minute
    ),
    CONSTRAINT chk_time_slots_status CHECK (
        status IN ('available', 'held', 'booked', 'blocked', 'maintenance', 'holiday')
    ),
    CONSTRAINT uq_time_slots UNIQUE (studio_id, slot_date, start_minute)
);
CREATE INDEX idx_time_slots_studio_date
    ON time_slots (studio_id, slot_date);
CREATE INDEX idx_time_slots_status_nonavail
    ON time_slots (studio_id, slot_date, status) WHERE status <> 'available';
CREATE INDEX idx_time_slots_booking
    ON time_slots (booking_id) WHERE booking_id IS NOT NULL;
CREATE INDEX idx_time_slots_hold_expires
    ON time_slots (hold_expires_at) WHERE status = 'held';


-- ============================================================================
-- 10. special_dates — 特殊日期（公休 / 假日 / 維護 / 包場 / 特殊時段 / 尖峰）
--    - date_type:
--        'closed'         — 全日休館
--        'holiday'        — 假日（可能只影響定價）
--        'maintenance'    — 維護（不開放）
--        'private_event'  — 包場（可能綁定 booking_id）
--        'special_hours'  — 特殊營業時段（覆蓋 business_hours）
--        'peak'           — 尖峰日（可能只影響定價）
--    - studio_id NULL：適用全部攝影棚
-- ============================================================================
CREATE TABLE special_dates (
    id                  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    studio_id           INTEGER        REFERENCES studios(id) ON DELETE CASCADE,
    special_date        DATE           NOT NULL,
    date_type           VARCHAR(32)    NOT NULL,
    name                VARCHAR(120),
    description         TEXT,
    start_minute        INTEGER,                                    -- special_hours 用
    end_minute          INTEGER,                                    -- special_hours 用
    price_multiplier    NUMERIC(4, 2)  NOT NULL DEFAULT 1.0,        -- peak/holiday 用
    booking_id          INTEGER,                                    -- private_event 綁定；FK 於 ALTER 補上
    is_recurring        BOOLEAN        NOT NULL DEFAULT FALSE,      -- 每年重複
    created_by_admin_id INTEGER        REFERENCES studio_admin_accounts(id) ON DELETE SET NULL,
    metadata            JSONB          NOT NULL DEFAULT '{}'::jsonb,
    created_at          TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_special_dates_type CHECK (
        date_type IN ('closed', 'holiday', 'maintenance', 'private_event', 'special_hours', 'peak')
    ),
    CONSTRAINT chk_special_dates_minutes CHECK (
        (start_minute IS NULL AND end_minute IS NULL) OR
        (start_minute BETWEEN 0 AND 1440 AND end_minute BETWEEN 0 AND 1440 AND end_minute > start_minute)
    )
);
CREATE INDEX idx_special_dates_studio_date
    ON special_dates (studio_id, special_date);
CREATE INDEX idx_special_dates_date
    ON special_dates (special_date);
CREATE INDEX idx_special_dates_type
    ON special_dates (date_type);


-- ============================================================================
-- 11. bookings — 預約單（核心）
--    - customer_account_id NULL 表示訪客預約（用姓名/電話/信箱識別）
--    - 顧客資料同時儲存於 booking 上，作為預約當下的 snapshot
--    - status / payment_status 見底部說明
-- ============================================================================
CREATE TABLE bookings (
    id                        INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    booking_number            VARCHAR(32)    NOT NULL,                     -- 顯示用：ODE-20260703-0001
    studio_id                 INTEGER        NOT NULL REFERENCES studios(id) ON DELETE RESTRICT,
    customer_account_id       INTEGER        REFERENCES customer_accounts(id) ON DELETE SET NULL,
    -- 顧客資料 snapshot
    customer_name             VARCHAR(100)   NOT NULL,
    customer_phone            VARCHAR(32)    NOT NULL,
    customer_email            VARCHAR(255)   NOT NULL,
    -- 實際時間（用 TIMESTAMPTZ，非 TIME/DATE 拆分）
    start_at                  TIMESTAMPTZ    NOT NULL,
    end_at                    TIMESTAMPTZ    NOT NULL,
    total_hours               NUMERIC(4, 2)  NOT NULL,                     -- 冗餘欄，方便報表
    -- 內容資訊
    headcount                 INTEGER,
    purpose                   VARCHAR(100),                                -- '人像' / '商品' / '影片'
    scene_ids                 JSONB          NOT NULL DEFAULT '[]'::jsonb, -- 選定佈景 id 列
    -- 金額
    pricing_plan_id           INTEGER        REFERENCES pricing_plans(id) ON DELETE SET NULL,
    subtotal                  NUMERIC(10, 2) NOT NULL,
    discount_amount           NUMERIC(10, 2) NOT NULL DEFAULT 0,
    discount_code             VARCHAR(64),
    tax_amount                NUMERIC(10, 2) NOT NULL DEFAULT 0,
    total_price               NUMERIC(10, 2) NOT NULL,
    deposit_amount            NUMERIC(10, 2) NOT NULL DEFAULT 0,
    -- 狀態（詳見底部）
    status                    VARCHAR(32)    NOT NULL DEFAULT 'pending',
    payment_status            VARCHAR(32)    NOT NULL DEFAULT 'unpaid',
    -- 備註
    customer_note             TEXT,
    admin_note                TEXT,
    -- 狀態時間戳
    confirmed_at              TIMESTAMPTZ,
    checked_in_at             TIMESTAMPTZ,
    completed_at              TIMESTAMPTZ,
    cancelled_at              TIMESTAMPTZ,
    cancellation_reason       TEXT,
    cancelled_by_admin_id     INTEGER        REFERENCES studio_admin_accounts(id) ON DELETE SET NULL,
    -- 來源
    source                    VARCHAR(32)    NOT NULL DEFAULT 'web',
    referral_code             VARCHAR(64),
    created_by_admin_id       INTEGER        REFERENCES studio_admin_accounts(id) ON DELETE SET NULL,
    -- 彈性欄
    metadata                  JSONB          NOT NULL DEFAULT '{}'::jsonb,
    created_at                TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at                TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_bookings_time CHECK (end_at > start_at),
    CONSTRAINT chk_bookings_status CHECK (
        status IN ('pending', 'confirmed', 'checked_in', 'completed', 'cancelled', 'no_show')
    ),
    CONSTRAINT chk_bookings_payment_status CHECK (
        payment_status IN ('unpaid', 'deposit_paid', 'paid', 'refund_pending', 'refunded', 'failed')
    ),
    CONSTRAINT chk_bookings_source CHECK (
        source IN ('web', 'phone', 'walk_in', 'admin')
    )
);
CREATE UNIQUE INDEX idx_bookings_number
    ON bookings (booking_number);
CREATE INDEX idx_bookings_studio_time
    ON bookings (studio_id, start_at, end_at);
CREATE INDEX idx_bookings_customer_account
    ON bookings (customer_account_id) WHERE customer_account_id IS NOT NULL;
CREATE INDEX idx_bookings_status
    ON bookings (status);
CREATE INDEX idx_bookings_payment_status
    ON bookings (payment_status);
CREATE INDEX idx_bookings_email
    ON bookings (LOWER(customer_email));
CREATE INDEX idx_bookings_phone
    ON bookings (customer_phone);
CREATE INDEX idx_bookings_start_at
    ON bookings (start_at);
CREATE INDEX idx_bookings_created_at
    ON bookings (created_at DESC);


-- ============================================================================
-- 12. payments — 付款單
--    - payment_method: 'bank_transfer'（匯款）/ 'ecpay_credit' / 'ecpay_atm' /
--                     'ecpay_cvs' / 'ecpay_barcode' / 'cash' / 'other'
--    - payment_type:   'deposit'（訂金）/ 'balance'（尾款）/ 'full' / 'refund'
--    - status:         'pending' | 'processing' | 'succeeded' | 'failed' | 'refunded' | 'cancelled'
--    - 綠界欄位全部預留，NULL 表示尚未使用
-- ============================================================================
CREATE TABLE payments (
    id                          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    booking_id                  INTEGER        NOT NULL REFERENCES bookings(id) ON DELETE RESTRICT,
    payment_number              VARCHAR(32)    NOT NULL,               -- 顯示用
    payment_method              VARCHAR(32)    NOT NULL,
    payment_type                VARCHAR(32)    NOT NULL DEFAULT 'full',
    amount                      NUMERIC(10, 2) NOT NULL,
    currency                    VARCHAR(8)     NOT NULL DEFAULT 'TWD',
    status                      VARCHAR(32)    NOT NULL DEFAULT 'pending',
    -- 匯款相關
    bank_account_id             INTEGER,                               -- FK 於 ALTER 補上
    payer_name                  VARCHAR(100),                          -- 匯款人姓名
    payer_last5                 VARCHAR(10),                           -- 匯款帳號末 5 碼
    transferred_at              TIMESTAMPTZ,                           -- 顧客回報匯款時間
    verified_at                 TIMESTAMPTZ,                           -- 後台核對通過時間
    verified_by_admin_id        INTEGER        REFERENCES studio_admin_accounts(id) ON DELETE SET NULL,
    -- 綠界 ECPay 預留欄位
    ecpay_merchant_trade_no     VARCHAR(64),
    ecpay_trade_no              VARCHAR(64),
    ecpay_payment_type          VARCHAR(32),
    ecpay_rtn_code              VARCHAR(16),
    ecpay_rtn_msg               VARCHAR(255),
    ecpay_paid_at               TIMESTAMPTZ,
    ecpay_check_mac_value       VARCHAR(255),
    ecpay_raw_response          JSONB,
    -- 退款
    refund_amount               NUMERIC(10, 2) NOT NULL DEFAULT 0,
    refunded_at                 TIMESTAMPTZ,
    refund_reason               TEXT,
    refunded_by_admin_id        INTEGER        REFERENCES studio_admin_accounts(id) ON DELETE SET NULL,
    -- 到期時間（例：綠界訂單、匯款倒數）
    expires_at                  TIMESTAMPTZ,
    metadata                    JSONB          NOT NULL DEFAULT '{}'::jsonb,
    created_at                  TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_payments_method CHECK (
        payment_method IN ('bank_transfer', 'ecpay_credit', 'ecpay_atm', 'ecpay_cvs',
                           'ecpay_barcode', 'cash', 'other')
    ),
    CONSTRAINT chk_payments_type CHECK (
        payment_type IN ('deposit', 'balance', 'full', 'refund')
    ),
    CONSTRAINT chk_payments_status CHECK (
        status IN ('pending', 'processing', 'succeeded', 'failed', 'refunded', 'cancelled')
    )
);
CREATE UNIQUE INDEX idx_payments_number
    ON payments (payment_number);
CREATE INDEX idx_payments_booking
    ON payments (booking_id);
CREATE INDEX idx_payments_status
    ON payments (status);
CREATE INDEX idx_payments_method
    ON payments (payment_method);
CREATE UNIQUE INDEX idx_payments_ecpay_trade
    ON payments (ecpay_merchant_trade_no) WHERE ecpay_merchant_trade_no IS NOT NULL;
CREATE INDEX idx_payments_transferred_at
    ON payments (transferred_at) WHERE transferred_at IS NOT NULL;


-- ============================================================================
-- 13. payment_logs — 付款事件記錄（金流稽核）
--    - 每一次狀態變更、webhook、顧客回報，都會產生一筆
--    - event_type：例 'created' / 'submitted' / 'verified' / 'failed' /
--                    'refund_requested' / 'refunded' / 'webhook_received'
--    - source：       'customer' / 'admin' / 'ecpay_webhook' / 'system'
-- ============================================================================
CREATE TABLE payment_logs (
    id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    payment_id      INTEGER      NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
    event_type      VARCHAR(64)  NOT NULL,
    from_status     VARCHAR(32),
    to_status       VARCHAR(32),
    source          VARCHAR(32)  NOT NULL DEFAULT 'system',
    admin_id        INTEGER      REFERENCES studio_admin_accounts(id) ON DELETE SET NULL,
    ip_address      VARCHAR(64),
    user_agent      TEXT,
    message         TEXT,
    payload         JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_payment_logs_source CHECK (
        source IN ('customer', 'admin', 'ecpay_webhook', 'system')
    )
);
CREATE INDEX idx_payment_logs_payment
    ON payment_logs (payment_id, created_at DESC);
CREATE INDEX idx_payment_logs_event_type
    ON payment_logs (event_type);
CREATE INDEX idx_payment_logs_created
    ON payment_logs (created_at DESC);


-- ============================================================================
-- 14. door_lock_codes — 電子鎖密碼
--    - 一筆 booking 通常對應一筆 code，於預約前一天由排程寄出
--    - scheduled_send_at 預設 = start_at - 24h（可依 system_settings 調整）
--    - send_status：'scheduled' / 'sending' / 'sent' / 'failed' / 'cancelled'
--    - 支援多種通道（email/sms/line）；MVP 用 email，其他預留
--    - lock_provider：'igloohome' / 'ttlock' / 'manual'
-- ============================================================================
CREATE TABLE door_lock_codes (
    id                        INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    booking_id                INTEGER      NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    studio_id                 INTEGER      NOT NULL REFERENCES studios(id) ON DELETE CASCADE,
    lock_code                 VARCHAR(32)  NOT NULL,                        -- 寄出的明文密碼
    lock_code_hash            VARCHAR(255),                                 -- 儲存端可只留 hash（可選）
    valid_from                TIMESTAMPTZ  NOT NULL,
    valid_until               TIMESTAMPTZ  NOT NULL,
    -- 寄送
    send_status               VARCHAR(32)  NOT NULL DEFAULT 'scheduled',
    scheduled_send_at         TIMESTAMPTZ  NOT NULL,
    sent_at                   TIMESTAMPTZ,
    delivery_channel          VARCHAR(32)  NOT NULL DEFAULT 'email',
    email_log_id              INTEGER,                                      -- FK 於 ALTER 補上
    send_attempts             INTEGER      NOT NULL DEFAULT 0,
    last_error                TEXT,
    -- 使用紀錄
    used_at                   TIMESTAMPTZ,
    used_count                INTEGER      NOT NULL DEFAULT 0,
    -- 鎖具資訊
    lock_device_id            VARCHAR(64),
    lock_provider             VARCHAR(32),
    provider_reference        VARCHAR(128),
    provider_raw              JSONB,
    -- 手動作業
    manually_sent_by_admin_id INTEGER      REFERENCES studio_admin_accounts(id) ON DELETE SET NULL,
    metadata                  JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at                TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at                TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_door_lock_send_status CHECK (
        send_status IN ('scheduled', 'sending', 'sent', 'failed', 'cancelled')
    ),
    CONSTRAINT chk_door_lock_channel CHECK (
        delivery_channel IN ('email', 'sms', 'line')
    ),
    CONSTRAINT chk_door_lock_time CHECK (valid_until > valid_from)
);
CREATE INDEX idx_door_lock_codes_booking
    ON door_lock_codes (booking_id);
CREATE INDEX idx_door_lock_codes_scheduled
    ON door_lock_codes (scheduled_send_at) WHERE send_status = 'scheduled';
CREATE INDEX idx_door_lock_codes_send_status
    ON door_lock_codes (send_status);
CREATE INDEX idx_door_lock_codes_valid
    ON door_lock_codes (valid_from, valid_until);


-- ============================================================================
-- 15. email_logs — Email 寄送紀錄
--    - 所有系統寄出的信皆入此表（預約確認、密碼、退款、行銷…）
--    - status：見底部說明。opened_at/clicked_at 由 webhook 更新
-- ============================================================================
CREATE TABLE email_logs (
    id                      INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email_template_id       INTEGER,                                  -- FK 於 ALTER 補上
    booking_id              INTEGER      REFERENCES bookings(id) ON DELETE SET NULL,
    customer_account_id     INTEGER      REFERENCES customer_accounts(id) ON DELETE SET NULL,
    -- 收件與寄件
    to_email                VARCHAR(255) NOT NULL,
    to_name                 VARCHAR(100),
    cc_emails               JSONB        NOT NULL DEFAULT '[]'::jsonb,
    bcc_emails              JSONB        NOT NULL DEFAULT '[]'::jsonb,
    from_email              VARCHAR(255) NOT NULL,
    from_name               VARCHAR(100),
    reply_to                VARCHAR(255),
    -- 內容 snapshot（渲染後）
    subject                 VARCHAR(255) NOT NULL,
    body_html               TEXT,
    body_text               TEXT,
    -- 分類
    email_type              VARCHAR(64)  NOT NULL,
    -- 狀態
    status                  VARCHAR(32)  NOT NULL DEFAULT 'queued',
    -- 供應商
    provider                VARCHAR(32),                              -- 'ses' / 'sendgrid' / 'mailgun' / 'smtp'
    provider_message_id     VARCHAR(128),
    -- 時間戳
    scheduled_at            TIMESTAMPTZ,
    sent_at                 TIMESTAMPTZ,
    delivered_at            TIMESTAMPTZ,
    opened_at               TIMESTAMPTZ,
    clicked_at              TIMESTAMPTZ,
    bounced_at              TIMESTAMPTZ,
    failed_at               TIMESTAMPTZ,
    send_attempts           INTEGER      NOT NULL DEFAULT 0,
    last_error              TEXT,
    -- 模板變數
    variables               JSONB        NOT NULL DEFAULT '{}'::jsonb,
    provider_response       JSONB,
    metadata                JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_email_logs_status CHECK (
        status IN ('queued', 'sending', 'sent', 'delivered', 'opened', 'clicked',
                   'bounced', 'spam', 'failed')
    )
);
CREATE INDEX idx_email_logs_booking
    ON email_logs (booking_id) WHERE booking_id IS NOT NULL;
CREATE INDEX idx_email_logs_customer_account
    ON email_logs (customer_account_id) WHERE customer_account_id IS NOT NULL;
CREATE INDEX idx_email_logs_to_email
    ON email_logs (LOWER(to_email));
CREATE INDEX idx_email_logs_status
    ON email_logs (status);
CREATE INDEX idx_email_logs_type
    ON email_logs (email_type);
CREATE INDEX idx_email_logs_scheduled
    ON email_logs (scheduled_at) WHERE status = 'queued';
CREATE UNIQUE INDEX idx_email_logs_provider_msg
    ON email_logs (provider, provider_message_id) WHERE provider_message_id IS NOT NULL;
CREATE INDEX idx_email_logs_created
    ON email_logs (created_at DESC);


-- ============================================================================
-- 16. email_templates — Email 模板
--    - template_key 為系統識別鍵（例：'booking_confirmation'）
--    - trigger_event / trigger_offset_minutes 可讓排程觸發
--    - 支援多語系（locale）
-- ============================================================================
CREATE TABLE email_templates (
    id                      INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    template_key            VARCHAR(64)  NOT NULL,
    name                    VARCHAR(120) NOT NULL,
    description             TEXT,
    email_type              VARCHAR(64)  NOT NULL,
    subject                 VARCHAR(255) NOT NULL,
    body_html               TEXT         NOT NULL,
    body_text               TEXT,
    from_email              VARCHAR(255),
    from_name               VARCHAR(100),
    reply_to                VARCHAR(255),
    available_variables     JSONB        NOT NULL DEFAULT '[]'::jsonb, -- ['booking_number','studio_name']
    trigger_event           VARCHAR(64),                                -- 'booking_created' 等
    trigger_offset_minutes  INTEGER,                                    -- 正=事件後 N 分鐘；負=事件前
    version                 INTEGER      NOT NULL DEFAULT 1,
    is_active               BOOLEAN      NOT NULL DEFAULT TRUE,
    locale                  VARCHAR(16)  NOT NULL DEFAULT 'zh-TW',
    updated_by_admin_id     INTEGER      REFERENCES studio_admin_accounts(id) ON DELETE SET NULL,
    metadata                JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at              TIMESTAMPTZ,
    CONSTRAINT uq_email_templates_key_locale UNIQUE (template_key, locale)
);
CREATE INDEX idx_email_templates_active
    ON email_templates (is_active, template_key) WHERE deleted_at IS NULL;
CREATE INDEX idx_email_templates_trigger_event
    ON email_templates (trigger_event) WHERE trigger_event IS NOT NULL;


-- ============================================================================
-- 17. bank_accounts — 收款銀行帳戶（攝影棚方）
--    - 匯款流程使用；顧客結帳頁面會顯示 is_active + is_default 的帳戶
--    - studio_id NULL 表示所有攝影棚共用
-- ============================================================================
CREATE TABLE bank_accounts (
    id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_name    VARCHAR(100) NOT NULL,                        -- 帳戶簡稱（管理用）
    bank_name       VARCHAR(100) NOT NULL,
    bank_code       VARCHAR(16)  NOT NULL,
    branch_name     VARCHAR(100),
    branch_code     VARCHAR(16),
    account_number  VARCHAR(64)  NOT NULL,
    account_holder  VARCHAR(100) NOT NULL,
    swift_code      VARCHAR(32),
    -- 顯示
    display_name    VARCHAR(100),                                 -- 前台顯示（例：「主要收款帳戶」）
    display_order   INTEGER      NOT NULL DEFAULT 0,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    is_default      BOOLEAN      NOT NULL DEFAULT FALSE,
    studio_id       INTEGER      REFERENCES studios(id) ON DELETE SET NULL,
    note            TEXT,
    metadata        JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ
);
CREATE INDEX idx_bank_accounts_active
    ON bank_accounts (is_active, display_order) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX idx_bank_accounts_default
    ON bank_accounts (is_default) WHERE is_default = TRUE AND deleted_at IS NULL;


-- ============================================================================
-- 18. system_settings — 系統設定（key-value）
--    - value 一律存 JSONB（可放字串、數字、布林、物件、陣列）
--    - value_type 標示前端 form 該如何 render
--    - is_public：可否由前台未登入取用（例：品牌名稱、公休提示）
--    - 常見 key：
--        booking.min_advance_hours       — 最少提前預約時數
--        booking.hold_minutes             — 結帳倒數（time_slots.held 有效時長）
--        payment.bank_transfer_deadline   — 匯款期限（小時）
--        payment.deposit_ratio            — 訂金比例（0.3 = 30%）
--        lock.send_offset_hours           — 密碼提前寄送小時數（預設 24）
--        email.from_email / email.from_name
--        branding.site_name / branding.logo_url
-- ============================================================================
CREATE TABLE system_settings (
    id                      INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    setting_key             VARCHAR(120) NOT NULL,
    setting_value           JSONB        NOT NULL DEFAULT 'null'::jsonb,
    value_type              VARCHAR(32)  NOT NULL DEFAULT 'json',
    category                VARCHAR(64)  NOT NULL DEFAULT 'general',
    display_name            VARCHAR(120),
    description             TEXT,
    is_public               BOOLEAN      NOT NULL DEFAULT FALSE,
    is_encrypted            BOOLEAN      NOT NULL DEFAULT FALSE,
    validation_rules        JSONB        NOT NULL DEFAULT '{}'::jsonb,
    updated_by_admin_id     INTEGER      REFERENCES studio_admin_accounts(id) ON DELETE SET NULL,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_system_settings_key UNIQUE (setting_key),
    CONSTRAINT chk_system_settings_type CHECK (
        value_type IN ('string', 'number', 'boolean', 'json')
    )
);
CREATE INDEX idx_system_settings_category
    ON system_settings (category);
CREATE INDEX idx_system_settings_public
    ON system_settings (is_public) WHERE is_public = TRUE;


-- ============================================================================
-- 19. admin_activity_logs — 後台操作紀錄（稽核）
--    - action：'login' / 'logout' / 'create' / 'update' / 'delete' /
--              'confirm_payment' / 'send_lock_code' / 'cancel_booking' ...
--    - changes：{ before: {...}, after: {...} }
-- ============================================================================
CREATE TABLE admin_activity_logs (
    id              INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    admin_id        INTEGER      REFERENCES studio_admin_accounts(id) ON DELETE SET NULL,
    action          VARCHAR(64)  NOT NULL,
    entity_type     VARCHAR(64),                                   -- 'booking' / 'payment' / 'studio' / ...
    entity_id       INTEGER,
    changes         JSONB        NOT NULL DEFAULT '{}'::jsonb,
    ip_address      VARCHAR(64),
    user_agent      TEXT,
    request_method  VARCHAR(16),
    request_path    VARCHAR(500),
    status          VARCHAR(32)  NOT NULL DEFAULT 'success',
    error_message   TEXT,
    metadata        JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_admin_activity_status CHECK (status IN ('success', 'failed'))
);
CREATE INDEX idx_admin_activity_admin
    ON admin_activity_logs (admin_id, created_at DESC);
CREATE INDEX idx_admin_activity_entity
    ON admin_activity_logs (entity_type, entity_id);
CREATE INDEX idx_admin_activity_action
    ON admin_activity_logs (action);
CREATE INDEX idx_admin_activity_created
    ON admin_activity_logs (created_at DESC);


-- ============================================================================
-- 補上循環參考的外鍵（因建立順序造成的 forward reference）
-- ============================================================================
ALTER TABLE time_slots
    ADD CONSTRAINT fk_time_slots_booking
    FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE SET NULL;

ALTER TABLE special_dates
    ADD CONSTRAINT fk_special_dates_booking
    FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE SET NULL;

ALTER TABLE payments
    ADD CONSTRAINT fk_payments_bank_account
    FOREIGN KEY (bank_account_id) REFERENCES bank_accounts(id) ON DELETE SET NULL;

ALTER TABLE door_lock_codes
    ADD CONSTRAINT fk_door_lock_codes_email_log
    FOREIGN KEY (email_log_id) REFERENCES email_logs(id) ON DELETE SET NULL;

ALTER TABLE email_logs
    ADD CONSTRAINT fk_email_logs_template
    FOREIGN KEY (email_template_id) REFERENCES email_templates(id) ON DELETE SET NULL;


-- ============================================================================
-- 註：本 schema 移除了 DB-level 的自動 updated_at 更新機制。
--
-- 原因
--   目標匯入器（SaaS auto-API 平台的 DDL parser）不接受：
--     - 建立使用者自訂函式（procedural language）
--     - 觸發器（trigger）
--     - dollar-quoted 字串語法
--   實測錯誤：`Expected ... "TRIGGER", "VIEW" ... but "F" found`
--   表示 parser 的 CREATE OR REPLACE 文法只允許 AGGREGATE / CONSTRAINT /
--   RECURSIVE / TEMP / TEMPORARY / TRIGGER / VIEW（沒有 procedure/function）。
--
-- 替代方案
--   1) 各表 updated_at 皆已設 DEFAULT NOW() NOT NULL；
--      INSERT 時免傳，DB 會自動填入建立時間。
--   2) UPDATE 時 updated_at 由「應用層」或「auto-API 平台」自動改寫：
--        - Directus / NocoDB / Xano / Supabase / PostgREST 皆內建此行為
--        - 若自行寫 API，於每次 UPDATE 加上 `SET updated_at = NOW()` 即可
--   3) 若日後遷移到完整 PostgreSQL 環境，可補上一支通用觸發器函式（於每次
--      BEFORE UPDATE 時把 updated_at 設為 NOW()），並替每張表掛上觸發器。
--
-- 例外：payment_logs 與 admin_activity_logs 是 append-only，無 updated_at 欄。
-- ============================================================================

-- ============================================================================
-- 附註：updated_at 的維護
--   本 schema 為配合限制型 SQL parser（不支援 CREATE FUNCTION），
--   已移除 set_updated_at() 觸發器。updated_at 的更新請由以下任一方式處理：
--     (a) 應用層在 UPDATE 前自行寫入 NOW()
--     (b) auto-API SaaS 平台（Directus/Supabase/PostgREST/Hasura）
--         皆有內建「auto-update timestamp」設定
--     (c) 若可直連 Postgres，另跑一份 triggers.sql 補回同樣行為
-- ============================================================================
