CREATE SCHEMA IF NOT EXISTS public;
 SET search_path TO public; 

CREATE TABLE "users" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"account" VARCHAR(100) NOT NULL,
	"provider" VARCHAR(50) NOT NULL,
	"password_hash" VARCHAR(255) NOT NULL,
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id"),
	UNIQUE ("provider", "account")
);
COMMENT ON TABLE "users" IS '使用者核心資料表 @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null},{"actor":"user","actions":["read","update"],"condition":{"field":"id","operator":"eq","target":"actor.id"}}]}';
COMMENT ON COLUMN "users"."id" IS '流水號';
COMMENT ON COLUMN "users"."account" IS '用戶帳號 (email/phone/google/github/line/etc.) @validate="required,email|e164"';
COMMENT ON COLUMN "users"."provider" IS '登入提供商 (email/phone/google/github/line/etc.)';
COMMENT ON COLUMN "users"."password_hash" IS '密碼雜湊 @type=encode @alias=password @rule=hide';
COMMENT ON COLUMN "users"."is_active" IS '是否啟用';
COMMENT ON COLUMN "users"."created_at" IS '資料建立時間 @type=auto_createdtime';
COMMENT ON COLUMN "users"."updated_at" IS '資料更新時間 @type=auto_updatedtime';
CREATE INDEX "user_account_index" ON "users" ("account");

CREATE TABLE "roles" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(100) NOT NULL UNIQUE,
	"description" TEXT,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);
COMMENT ON TABLE "roles" IS '角色定義表 @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null},{"actor":"user","actions":["read"],"condition":null}]}';
COMMENT ON COLUMN "roles"."id" IS '流水號';
COMMENT ON COLUMN "roles"."name" IS '角色名稱';
COMMENT ON COLUMN "roles"."description" IS '角色描述';
COMMENT ON COLUMN "roles"."created_at" IS '資料新增時間 @type=auto_createdtime';
COMMENT ON COLUMN "roles"."updated_at" IS '資料更新時間 @type=auto_updatedtime';

CREATE TABLE "user_roles" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"role_id" INTEGER NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id"),
	UNIQUE ("user_id", "role_id")
);
COMMENT ON TABLE "user_roles" IS '使用者與角色的關聯表 @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null},{"actor":"user","actions":["read"],"condition":{"field":"user_id","operator":"eq","target":"actor.id"}}]}';
COMMENT ON COLUMN "user_roles"."id" IS '流水號';
COMMENT ON COLUMN "user_roles"."user_id" IS '用戶流水號';
COMMENT ON COLUMN "user_roles"."role_id" IS '角色流水號';
COMMENT ON COLUMN "user_roles"."created_at" IS '資料建立時間 @type=auto_createdtime';
COMMENT ON COLUMN "user_roles"."updated_at" IS '資料更新時間 @type=auto_updatedtime';
CREATE INDEX "user_roles_user_id_index" ON "user_roles" ("user_id");

CREATE TABLE "customer_accounts" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"email" VARCHAR(255) NOT NULL,
	"phone" VARCHAR(32),
	"display_name" VARCHAR(100),
	"password_hash" VARCHAR(255),
	"email_verified_at" TIMESTAMPTZ,
	"phone_verified_at" TIMESTAMPTZ,
	"marketing_opt_in" BOOLEAN NOT NULL DEFAULT false,
	"last_login_at" TIMESTAMPTZ,
	"locale" VARCHAR(16) NOT NULL DEFAULT 'zh-TW',
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"deleted_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);
COMMENT ON TABLE "customer_accounts" IS 'customer_accounts @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "customer_accounts"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "customer_accounts"."updated_at" IS '@type=auto_updatedtime';
CREATE UNIQUE INDEX "idx_customer_accounts_email" ON "customer_accounts" (LOWER(email));
CREATE INDEX "idx_customer_accounts_phone" ON "customer_accounts" ("phone");
CREATE INDEX "idx_customer_accounts_active" ON "customer_accounts" ("is_active");

CREATE TABLE "studio_admin_accounts" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"email" VARCHAR(255) NOT NULL,
	"display_name" VARCHAR(100) NOT NULL,
	"password_hash" VARCHAR(255) NOT NULL,
	"role" VARCHAR(32) NOT NULL DEFAULT 'staff',
	"last_login_at" TIMESTAMPTZ,
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"deleted_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);
COMMENT ON TABLE "studio_admin_accounts" IS 'studio_admin_accounts @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "studio_admin_accounts"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "studio_admin_accounts"."updated_at" IS '@type=auto_updatedtime';
CREATE UNIQUE INDEX "idx_studio_admin_accounts_email" ON "studio_admin_accounts" (LOWER(email));
CREATE INDEX "idx_studio_admin_accounts_active" ON "studio_admin_accounts" ("is_active");

CREATE TABLE "studios" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"slug" VARCHAR(64) NOT NULL,
	"name" VARCHAR(120) NOT NULL,
	"description" TEXT,
	"address" VARCHAR(255),
	"floor" VARCHAR(32),
	"area_ping" NUMERIC(6,2),
	"capacity" INTEGER,
	"features" JSONB NOT NULL DEFAULT '[]',
	"default_hourly_price" NUMERIC(10,2) NOT NULL,
	"min_booking_minutes" INTEGER NOT NULL DEFAULT 60,
	"max_booking_minutes" INTEGER NOT NULL DEFAULT 480,
	"booking_increment_minutes" INTEGER NOT NULL DEFAULT 30,
	"advance_booking_days" INTEGER NOT NULL DEFAULT 90,
	"cancellation_hours" INTEGER NOT NULL DEFAULT 48,
	"display_order" INTEGER NOT NULL DEFAULT 0,
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"deleted_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);
COMMENT ON TABLE "studios" IS 'studios @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "studios"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "studios"."updated_at" IS '@type=auto_updatedtime';
CREATE UNIQUE INDEX "idx_studios_slug" ON "studios" ("slug");
CREATE INDEX "idx_studios_active_order" ON "studios" ("is_active", "display_order");

CREATE TABLE "studio_images" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"studio_id" INTEGER NOT NULL,
	"url" VARCHAR(500) NOT NULL,
	"alt_text" VARCHAR(255),
	"caption" VARCHAR(255),
	"display_order" INTEGER NOT NULL DEFAULT 0,
	"is_cover" BOOLEAN NOT NULL DEFAULT false,
	"width" INTEGER,
	"height" INTEGER,
	"file_size" INTEGER,
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);
COMMENT ON TABLE "studio_images" IS 'studio_images @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "studio_images"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "studio_images"."updated_at" IS '@type=auto_updatedtime';
CREATE INDEX "idx_studio_images_studio" ON "studio_images" ("studio_id", "display_order");
CREATE UNIQUE INDEX "idx_studio_images_cover" ON "studio_images" ("studio_id");

CREATE TABLE "scenes" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"studio_id" INTEGER NOT NULL,
	"slug" VARCHAR(64) NOT NULL,
	"name" VARCHAR(120) NOT NULL,
	"description" TEXT,
	"tags" JSONB NOT NULL DEFAULT '[]',
	"display_order" INTEGER NOT NULL DEFAULT 0,
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"deleted_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);
COMMENT ON TABLE "scenes" IS 'scenes @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "scenes"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "scenes"."updated_at" IS '@type=auto_updatedtime';
CREATE INDEX "idx_scenes_studio" ON "scenes" ("studio_id", "display_order");

CREATE TABLE "scene_images" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"scene_id" INTEGER NOT NULL,
	"url" VARCHAR(500) NOT NULL,
	"alt_text" VARCHAR(255),
	"caption" VARCHAR(255),
	"display_order" INTEGER NOT NULL DEFAULT 0,
	"is_cover" BOOLEAN NOT NULL DEFAULT false,
	"width" INTEGER,
	"height" INTEGER,
	"file_size" INTEGER,
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);
COMMENT ON TABLE "scene_images" IS 'scene_images @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "scene_images"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "scene_images"."updated_at" IS '@type=auto_updatedtime';
CREATE INDEX "idx_scene_images_scene" ON "scene_images" ("scene_id", "display_order");
CREATE INDEX "idx_scene_images_cover" ON "scene_images" ("scene_id");

CREATE TABLE "pricing_plans" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"studio_id" INTEGER NOT NULL,
	"name" VARCHAR(100) NOT NULL,
	"plan_type" VARCHAR(32) NOT NULL DEFAULT 'hourly',
	"hourly_price" NUMERIC(10,2) NOT NULL,
	"package_price" NUMERIC(10,2),
	"package_hours" NUMERIC(4,2),
	"applies_to_weekdays" JSONB NOT NULL DEFAULT '[0,1,2,3,4,5,6]',
	"start_minute" INTEGER,
	"end_minute" INTEGER,
	"effective_from" DATE,
	"effective_to" DATE,
	"min_hours" NUMERIC(4,2) NOT NULL DEFAULT 1,
	"max_hours" NUMERIC(4,2),
	"priority" INTEGER NOT NULL DEFAULT 0,
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"deleted_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);
COMMENT ON TABLE "pricing_plans" IS 'pricing_plans @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "pricing_plans"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "pricing_plans"."updated_at" IS '@type=auto_updatedtime';
CREATE INDEX "idx_pricing_plans_studio_priority" ON "pricing_plans" ("studio_id", "priority");

CREATE TABLE "business_hours" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"studio_id" INTEGER NOT NULL,
	"weekday" INTEGER,
	"start_minute" INTEGER,
	"end_minute" INTEGER,
	"is_closed" BOOLEAN NOT NULL DEFAULT false,
	"note" VARCHAR(255),
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);
COMMENT ON TABLE "business_hours" IS 'business_hours @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":{"field":"","operator":"eq","target":"actor.id"}}]}';
COMMENT ON COLUMN "business_hours"."weekday" IS '@validate="numeric,gte=0,lte=6"';
COMMENT ON COLUMN "business_hours"."start_minute" IS '@validate="numeric,gte=0,lte=1439"';
COMMENT ON COLUMN "business_hours"."end_minute" IS '@validate="numeric,gte=0,lte=1440"';
COMMENT ON COLUMN "business_hours"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "business_hours"."updated_at" IS '@type=auto_updatedtime';
CREATE INDEX "idx_business_hours_studio" ON "business_hours" ("studio_id", "weekday");

CREATE TABLE "time_slots" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"studio_id" INTEGER NOT NULL,
	"slot_date" DATE NOT NULL,
	"start_minute" INTEGER,
	"end_minute" INTEGER,
	"status" VARCHAR(32) NOT NULL DEFAULT 'available',
	"booking_id" INTEGER,
	"hourly_price" NUMERIC(10,2),
	"hold_expires_at" TIMESTAMPTZ,
	"block_reason" VARCHAR(255),
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);
COMMENT ON TABLE "time_slots" IS 'time_slots @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "time_slots"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "time_slots"."updated_at" IS '@type=auto_updatedtime';
CREATE INDEX "idx_time_slots_studio_date" ON "time_slots" ("studio_id", "slot_date");
CREATE INDEX "idx_time_slots_status_nonavail" ON "time_slots" ("studio_id", "slot_date", "status");
CREATE INDEX "idx_time_slots_booking" ON "time_slots" ("booking_id");
CREATE INDEX "idx_time_slots_hold_expires" ON "time_slots" ("hold_expires_at");

CREATE TABLE "special_dates" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"studio_id" INTEGER,
	"special_date" DATE NOT NULL,
	"date_type" VARCHAR(32) NOT NULL,
	"name" VARCHAR(120),
	"description" TEXT,
	"start_minute" INTEGER,
	"end_minute" INTEGER,
	"price_multiplier" NUMERIC(4,2) NOT NULL DEFAULT 1.0,
	"booking_id" INTEGER,
	"is_recurring" BOOLEAN NOT NULL DEFAULT false,
	"created_by_admin_id" INTEGER,
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);
COMMENT ON TABLE "special_dates" IS 'special_dates @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "special_dates"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "special_dates"."updated_at" IS '@type=auto_updatedtime';
CREATE INDEX "idx_special_dates_studio_date" ON "special_dates" ("studio_id", "special_date");
CREATE INDEX "idx_special_dates_date" ON "special_dates" ("special_date");
CREATE INDEX "idx_special_dates_type" ON "special_dates" ("date_type");

CREATE TABLE "bookings" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"booking_number" VARCHAR(32) NOT NULL,
	"studio_id" INTEGER NOT NULL,
	"customer_account_id" INTEGER,
	"customer_name" VARCHAR(100) NOT NULL,
	"customer_phone" VARCHAR(32) NOT NULL,
	"customer_email" VARCHAR(255) NOT NULL,
	"start_at" TIMESTAMPTZ NOT NULL,
	"end_at" TIMESTAMPTZ NOT NULL,
	"total_hours" NUMERIC(4,2) NOT NULL,
	"headcount" INTEGER,
	"purpose" VARCHAR(100),
	"scene_ids" JSONB NOT NULL DEFAULT '[]',
	"pricing_plan_id" INTEGER,
	"subtotal" NUMERIC(10,2) NOT NULL,
	"discount_amount" NUMERIC(10,2) NOT NULL DEFAULT 0,
	"discount_code" VARCHAR(64),
	"tax_amount" NUMERIC(10,2) NOT NULL DEFAULT 0,
	"total_price" NUMERIC(10,2) NOT NULL,
	"deposit_amount" NUMERIC(10,2) NOT NULL DEFAULT 0,
	"status" VARCHAR(32) NOT NULL DEFAULT 'pending',
	"payment_status" VARCHAR(32) NOT NULL DEFAULT 'unpaid',
	"customer_note" TEXT,
	"admin_note" TEXT,
	"confirmed_at" TIMESTAMPTZ,
	"checked_in_at" TIMESTAMPTZ,
	"completed_at" TIMESTAMPTZ,
	"cancelled_at" TIMESTAMPTZ,
	"cancellation_reason" TEXT,
	"cancelled_by_admin_id" INTEGER,
	"source" VARCHAR(32) NOT NULL DEFAULT 'web',
	"referral_code" VARCHAR(64),
	"created_by_admin_id" INTEGER,
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"subtotal_price" INTEGER,
	"booking_mode" VARCHAR(32) NOT NULL DEFAULT 'scenes',
	PRIMARY KEY("id")
);
COMMENT ON TABLE "bookings" IS 'bookings @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "bookings"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "bookings"."updated_at" IS '@type=auto_updatedtime';
CREATE UNIQUE INDEX "idx_bookings_number" ON "bookings" ("booking_number");
CREATE INDEX "idx_bookings_studio_time" ON "bookings" ("studio_id", "start_at", "end_at");
CREATE INDEX "idx_bookings_customer_account" ON "bookings" ("customer_account_id");
CREATE INDEX "idx_bookings_status" ON "bookings" ("status");
CREATE INDEX "idx_bookings_payment_status" ON "bookings" ("payment_status");
CREATE INDEX "idx_bookings_email" ON "bookings" (LOWER(customer_email));
CREATE INDEX "idx_bookings_phone" ON "bookings" ("customer_phone");
CREATE INDEX "idx_bookings_start_at" ON "bookings" ("start_at");
CREATE INDEX "idx_bookings_created_at" ON "bookings" ("created_at");
CREATE INDEX "bookings_index_9" ON "bookings" ("discount_code");

CREATE TABLE "payments" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"booking_id" INTEGER NOT NULL,
	"payment_number" VARCHAR(32) NOT NULL,
	"payment_method" VARCHAR(32) NOT NULL,
	"payment_type" VARCHAR(32) NOT NULL DEFAULT 'full',
	"amount" NUMERIC(10,2) NOT NULL,
	"currency" VARCHAR(8) NOT NULL DEFAULT 'TWD',
	"status" VARCHAR(32) NOT NULL DEFAULT 'pending',
	"bank_account_id" INTEGER,
	"payer_name" VARCHAR(100),
	"payer_last5" VARCHAR(10),
	"transferred_at" TIMESTAMPTZ,
	"verified_at" TIMESTAMPTZ,
	"verified_by_admin_id" INTEGER,
	"ecpay_merchant_trade_no" VARCHAR(64),
	"ecpay_trade_no" VARCHAR(64),
	"ecpay_payment_type" VARCHAR(32),
	"ecpay_rtn_code" VARCHAR(16),
	"ecpay_rtn_msg" VARCHAR(255),
	"ecpay_paid_at" TIMESTAMPTZ,
	"ecpay_check_mac_value" VARCHAR(255),
	"ecpay_raw_response" JSONB,
	"refund_amount" NUMERIC(10,2) NOT NULL DEFAULT 0,
	"refunded_at" TIMESTAMPTZ,
	"refund_reason" TEXT,
	"refunded_by_admin_id" INTEGER,
	"expires_at" TIMESTAMPTZ,
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);
COMMENT ON TABLE "payments" IS 'payments @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "payments"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "payments"."updated_at" IS '@type=auto_updatedtime';
CREATE UNIQUE INDEX "idx_payments_number" ON "payments" ("payment_number");
CREATE INDEX "idx_payments_booking" ON "payments" ("booking_id");
CREATE INDEX "idx_payments_status" ON "payments" ("status");
CREATE INDEX "idx_payments_method" ON "payments" ("payment_method");
CREATE UNIQUE INDEX "idx_payments_ecpay_trade" ON "payments" ("ecpay_merchant_trade_no");
CREATE INDEX "idx_payments_transferred_at" ON "payments" ("transferred_at");

CREATE TABLE "payment_logs" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"payment_id" INTEGER NOT NULL,
	"event_type" VARCHAR(64) NOT NULL,
	"from_status" VARCHAR(32),
	"to_status" VARCHAR(32),
	"source" VARCHAR(32) NOT NULL DEFAULT 'system',
	"admin_id" INTEGER,
	"ip_address" VARCHAR(64),
	"user_agent" TEXT,
	"message" TEXT,
	"payload" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);
COMMENT ON TABLE "payment_logs" IS 'payment_logs @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "payment_logs"."created_at" IS '@type=auto_createdtime';
CREATE INDEX "idx_payment_logs_payment" ON "payment_logs" ("payment_id", "created_at");
CREATE INDEX "idx_payment_logs_event_type" ON "payment_logs" ("event_type");
CREATE INDEX "idx_payment_logs_created" ON "payment_logs" ("created_at");

CREATE TABLE "door_lock_codes" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"booking_id" INTEGER NOT NULL,
	"studio_id" INTEGER NOT NULL,
	"lock_code" VARCHAR(32) NOT NULL,
	"lock_code_hash" VARCHAR(255),
	"valid_from" TIMESTAMPTZ NOT NULL,
	"valid_until" TIMESTAMPTZ NOT NULL,
	"send_status" VARCHAR(32) NOT NULL DEFAULT 'scheduled',
	"scheduled_send_at" TIMESTAMPTZ NOT NULL,
	"sent_at" TIMESTAMPTZ,
	"delivery_channel" VARCHAR(32) NOT NULL DEFAULT 'email',
	"email_log_id" INTEGER,
	"send_attempts" INTEGER NOT NULL DEFAULT 0,
	"last_error" TEXT,
	"used_at" TIMESTAMPTZ,
	"used_count" INTEGER NOT NULL DEFAULT 0,
	"lock_device_id" VARCHAR(64),
	"lock_provider" VARCHAR(32),
	"provider_reference" VARCHAR(128),
	"provider_raw" JSONB,
	"manually_sent_by_admin_id" INTEGER,
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);
COMMENT ON TABLE "door_lock_codes" IS 'door_lock_codes @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "door_lock_codes"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "door_lock_codes"."updated_at" IS '@type=auto_updatedtime';
CREATE INDEX "idx_door_lock_codes_booking" ON "door_lock_codes" ("booking_id");
CREATE INDEX "idx_door_lock_codes_scheduled" ON "door_lock_codes" ("scheduled_send_at");
CREATE INDEX "idx_door_lock_codes_send_status" ON "door_lock_codes" ("send_status");
CREATE INDEX "idx_door_lock_codes_valid" ON "door_lock_codes" ("valid_from", "valid_until");

CREATE TABLE "email_logs" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"email_template_id" INTEGER,
	"booking_id" INTEGER,
	"customer_account_id" INTEGER,
	"to_email" VARCHAR(255) NOT NULL,
	"to_name" VARCHAR(100),
	"cc_emails" JSONB NOT NULL DEFAULT '[]',
	"bcc_emails" JSONB NOT NULL DEFAULT '[]',
	"from_email" VARCHAR(255) NOT NULL,
	"from_name" VARCHAR(100),
	"reply_to" VARCHAR(255),
	"subject" VARCHAR(255) NOT NULL,
	"body_html" TEXT,
	"body_text" TEXT,
	"email_type" VARCHAR(64) NOT NULL,
	"status" VARCHAR(32) NOT NULL DEFAULT 'queued',
	"provider" VARCHAR(32),
	"provider_message_id" VARCHAR(128),
	"scheduled_at" TIMESTAMPTZ,
	"sent_at" TIMESTAMPTZ,
	"delivered_at" TIMESTAMPTZ,
	"opened_at" TIMESTAMPTZ,
	"clicked_at" TIMESTAMPTZ,
	"bounced_at" TIMESTAMPTZ,
	"failed_at" TIMESTAMPTZ,
	"send_attempts" INTEGER NOT NULL DEFAULT 0,
	"last_error" TEXT,
	"variables" JSONB NOT NULL DEFAULT '{}',
	"provider_response" JSONB,
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);
COMMENT ON TABLE "email_logs" IS 'email_logs @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "email_logs"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "email_logs"."updated_at" IS '@type=auto_updatedtime';
CREATE INDEX "idx_email_logs_booking" ON "email_logs" ("booking_id");
CREATE INDEX "idx_email_logs_customer_account" ON "email_logs" ("customer_account_id");
CREATE INDEX "idx_email_logs_to_email" ON "email_logs" (LOWER(to_email));
CREATE INDEX "idx_email_logs_status" ON "email_logs" ("status");
CREATE INDEX "idx_email_logs_type" ON "email_logs" ("email_type");
CREATE INDEX "idx_email_logs_scheduled" ON "email_logs" ("scheduled_at");
CREATE UNIQUE INDEX "idx_email_logs_provider_msg" ON "email_logs" ("provider", "provider_message_id");
CREATE INDEX "idx_email_logs_created" ON "email_logs" ("created_at");

CREATE TABLE "email_templates" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"template_key" VARCHAR(64) NOT NULL,
	"name" VARCHAR(120) NOT NULL,
	"description" TEXT,
	"email_type" VARCHAR(64) NOT NULL,
	"subject" VARCHAR(255) NOT NULL,
	"body_html" TEXT NOT NULL,
	"body_text" TEXT,
	"from_email" VARCHAR(255),
	"from_name" VARCHAR(100),
	"reply_to" VARCHAR(255),
	"available_variables" JSONB NOT NULL DEFAULT '[]',
	"trigger_event" VARCHAR(64),
	"trigger_offset_minutes" INTEGER,
	"version" INTEGER NOT NULL DEFAULT 1,
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	"locale" VARCHAR(16) NOT NULL DEFAULT 'zh-TW',
	"updated_by_admin_id" INTEGER,
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"deleted_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);
COMMENT ON TABLE "email_templates" IS 'email_templates @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "email_templates"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "email_templates"."updated_at" IS '@type=auto_updatedtime';
CREATE INDEX "idx_email_templates_active" ON "email_templates" ("is_active", "template_key");
CREATE INDEX "idx_email_templates_trigger_event" ON "email_templates" ("trigger_event");

CREATE TABLE "bank_accounts" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"account_name" VARCHAR(100) NOT NULL,
	"bank_name" VARCHAR(100) NOT NULL,
	"bank_code" VARCHAR(16),
	"branch_name" VARCHAR(100),
	"branch_code" VARCHAR(16),
	"account_number" VARCHAR(64),
	"account_holder" VARCHAR(100),
	"swift_code" VARCHAR(32),
	"display_name" VARCHAR(100),
	"display_order" INTEGER DEFAULT 0,
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	"is_default" BOOLEAN NOT NULL DEFAULT false,
	"studio_id" INTEGER,
	"note" TEXT,
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"deleted_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);
COMMENT ON TABLE "bank_accounts" IS 'bank_accounts @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "bank_accounts"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "bank_accounts"."updated_at" IS '@type=auto_updatedtime';
CREATE INDEX "idx_bank_accounts_active" ON "bank_accounts" ("is_active", "display_order");
CREATE UNIQUE INDEX "idx_bank_accounts_default" ON "bank_accounts" ("is_default");

CREATE TABLE "system_settings" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"setting_key" VARCHAR(120) NOT NULL,
	"setting_value" JSONB DEFAULT null,
	"value_type" VARCHAR(32) NOT NULL DEFAULT 'json',
	"category" VARCHAR(64) NOT NULL DEFAULT 'general',
	"display_name" VARCHAR(120),
	"description" TEXT,
	"is_public" BOOLEAN NOT NULL DEFAULT false,
	"is_encrypted" BOOLEAN NOT NULL DEFAULT false,
	"validation_rules" JSONB NOT NULL DEFAULT '{}',
	"updated_by_admin_id" INTEGER,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);
COMMENT ON TABLE "system_settings" IS 'system_settings @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "system_settings"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "system_settings"."updated_at" IS '@type=auto_updatedtime';
CREATE INDEX "idx_system_settings_category" ON "system_settings" ("category");
CREATE INDEX "idx_system_settings_public" ON "system_settings" ("is_public");

CREATE TABLE "admin_activity_logs" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"admin_id" INTEGER,
	"action" VARCHAR(64) NOT NULL,
	"entity_type" VARCHAR(64),
	"entity_id" INTEGER,
	"changes" JSONB NOT NULL DEFAULT '{}',
	"ip_address" VARCHAR(64),
	"user_agent" TEXT,
	"request_method" VARCHAR(16),
	"request_path" VARCHAR(500),
	"status" VARCHAR(32) NOT NULL DEFAULT 'success',
	"error_message" TEXT,
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);
COMMENT ON TABLE "admin_activity_logs" IS 'admin_activity_logs @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "admin_activity_logs"."created_at" IS '@type=auto_createdtime';
CREATE INDEX "idx_admin_activity_admin" ON "admin_activity_logs" ("admin_id", "created_at");
CREATE INDEX "idx_admin_activity_entity" ON "admin_activity_logs" ("entity_type", "entity_id");
CREATE INDEX "idx_admin_activity_action" ON "admin_activity_logs" ("action");
CREATE INDEX "idx_admin_activity_created" ON "admin_activity_logs" ("created_at");

CREATE TABLE "discount_codes" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" TEXT NOT NULL UNIQUE,
	"name" TEXT,
	"discount_type" TEXT NOT NULL,
	"discount_amount" INTEGER NOT NULL,
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	"metadata" JSONB NOT NULL,
	PRIMARY KEY("id")
);
COMMENT ON TABLE "discount_codes" IS 'table_22 @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "discount_codes"."id" IS '流水號';

CREATE TABLE "studio_daily_availability" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"studio_id" INTEGER NOT NULL,
	"availability_date" DATE NOT NULL,
	"total_count" INTEGER NOT NULL DEFAULT 0,
	"available_count" INTEGER NOT NULL DEFAULT 0,
	"held_count" INTEGER NOT NULL DEFAULT 0,
	"booked_count" INTEGER NOT NULL DEFAULT 0,
	"blocked_count" INTEGER NOT NULL DEFAULT 0,
	"maintenance_count" INTEGER NOT NULL DEFAULT 0,
	"holiday_count" INTEGER NOT NULL DEFAULT 0,
	"is_closed" BOOLEAN NOT NULL DEFAULT false,
	"open_start_minute" INTEGER,
	"open_end_minute" INTEGER,
	"min_hourly_price" NUMERIC(10,2),
	"max_hourly_price" NUMERIC(10,2),
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);
COMMENT ON TABLE "studio_daily_availability" IS 'studio_daily_availability @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "studio_daily_availability"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "studio_daily_availability"."updated_at" IS '@type=auto_updatedtime';
CREATE INDEX "idx_studio_daily_availability_studio_date" ON "studio_daily_availability" ("studio_id", "availability_date");
CREATE INDEX "idx_studio_daily_availability_date" ON "studio_daily_availability" ("availability_date");

CREATE TABLE "scene_prices" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"scene_id" INTEGER NOT NULL,
	"hourly_price" NUMERIC(10,2) NOT NULL,
	"effective_from" DATE,
	"effective_to" DATE,
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);
COMMENT ON TABLE "scene_prices" IS 'scene_prices @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "scene_prices"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "scene_prices"."updated_at" IS '@type=auto_updatedtime';
CREATE INDEX "idx_scene_prices_scene" ON "scene_prices" ("scene_id");
CREATE INDEX "idx_scene_prices_active" ON "scene_prices" ("is_active");

CREATE TABLE "studio_prices" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"studio_id" INTEGER NOT NULL,
	"price_type" VARCHAR(32) NOT NULL DEFAULT 'buyout',
	"hourly_price" NUMERIC(10,2) NOT NULL,
	"effective_from" DATE,
	"effective_to" DATE,
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);
COMMENT ON TABLE "studio_prices" IS 'studio_prices @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "studio_prices"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "studio_prices"."updated_at" IS '@type=auto_updatedtime';
CREATE INDEX "idx_studio_prices_studio" ON "studio_prices" ("studio_id");
CREATE INDEX "idx_studio_prices_type_active" ON "studio_prices" ("price_type", "is_active");

CREATE TABLE "booking_scene_time_slots" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"booking_id" INTEGER NOT NULL,
	"scene_id" INTEGER NOT NULL,
	"time_slot_id" INTEGER NOT NULL,
	"status" VARCHAR(32) NOT NULL DEFAULT 'active',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"cancelled_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);
COMMENT ON TABLE "booking_scene_time_slots" IS 'booking_scene_time_slots @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "booking_scene_time_slots"."created_at" IS '@type=auto_createdtime';
CREATE INDEX "idx_booking_scene_time_slots_booking" ON "booking_scene_time_slots" ("booking_id");
CREATE INDEX "idx_booking_scene_time_slots_scene" ON "booking_scene_time_slots" ("scene_id");
CREATE INDEX "idx_booking_scene_time_slots_time_slot" ON "booking_scene_time_slots" ("time_slot_id");
CREATE UNIQUE INDEX "uq_booking_scene_time_slots_active" ON "booking_scene_time_slots" ("scene_id", "time_slot_id");

CREATE TABLE "equipment_items" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(120) NOT NULL,
	"description" TEXT,
	"unit_price" NUMERIC(10,2) NOT NULL DEFAULT 0,
	"image_url" TEXT,
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	"display_order" INTEGER NOT NULL DEFAULT 0,
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);
COMMENT ON TABLE "equipment_items" IS 'equipment_items @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "equipment_items"."created_at" IS '@type=auto_createdtime';
COMMENT ON COLUMN "equipment_items"."updated_at" IS '@type=auto_updatedtime';
CREATE INDEX "idx_equipment_items_active_order" ON "equipment_items" ("is_active", "display_order");

CREATE TABLE "booking_equipment_items" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"booking_id" INTEGER NOT NULL,
	"equipment_item_id" INTEGER NOT NULL,
	"name" VARCHAR(120) NOT NULL,
	"quantity" INTEGER NOT NULL DEFAULT 1,
	"unit_price" NUMERIC(10,2) NOT NULL DEFAULT 0,
	"subtotal" NUMERIC(10,2) NOT NULL DEFAULT 0,
	"metadata" JSONB NOT NULL DEFAULT '{}',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);
COMMENT ON TABLE "booking_equipment_items" IS 'booking_equipment_items @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "booking_equipment_items"."created_at" IS '@type=auto_createdtime';
CREATE INDEX "idx_booking_equipment_items_booking" ON "booking_equipment_items" ("booking_id");

CREATE TABLE "booking_equipment_time_slots" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"booking_id" INTEGER NOT NULL,
	"equipment_item_id" INTEGER NOT NULL,
	"time_slot_id" INTEGER NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY("id")
);
COMMENT ON TABLE "booking_equipment_time_slots" IS 'booking_equipment_time_slots @oso={"rules":[{"actor":"admin","actions":["read","create","update","delete"],"condition":null}]}';
COMMENT ON COLUMN "booking_equipment_time_slots"."created_at" IS '@type=auto_createdtime';
CREATE UNIQUE INDEX "uq_booking_equipment_time_slot" ON "booking_equipment_time_slots" ("equipment_item_id", "time_slot_id");
CREATE INDEX "idx_booking_equipment_time_slots_booking" ON "booking_equipment_time_slots" ("booking_id");
CREATE INDEX "idx_booking_equipment_time_slots_time_slot" ON "booking_equipment_time_slots" ("time_slot_id");
ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "user_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "studio_images" ADD FOREIGN KEY ("studio_id") REFERENCES "studios" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "scenes" ADD FOREIGN KEY ("studio_id") REFERENCES "studios" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "scene_images" ADD FOREIGN KEY ("scene_id") REFERENCES "scenes" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "pricing_plans" ADD FOREIGN KEY ("studio_id") REFERENCES "studios" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "business_hours" ADD FOREIGN KEY ("studio_id") REFERENCES "studios" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "time_slots" ADD FOREIGN KEY ("studio_id") REFERENCES "studios" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "special_dates" ADD FOREIGN KEY ("studio_id") REFERENCES "studios" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "special_dates" ADD FOREIGN KEY ("created_by_admin_id") REFERENCES "studio_admin_accounts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "bookings" ADD FOREIGN KEY ("studio_id") REFERENCES "studios" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "bookings" ADD FOREIGN KEY ("customer_account_id") REFERENCES "customer_accounts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "bookings" ADD FOREIGN KEY ("pricing_plan_id") REFERENCES "pricing_plans" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "bookings" ADD FOREIGN KEY ("cancelled_by_admin_id") REFERENCES "studio_admin_accounts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "bookings" ADD FOREIGN KEY ("created_by_admin_id") REFERENCES "studio_admin_accounts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "payments" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "payments" ADD FOREIGN KEY ("verified_by_admin_id") REFERENCES "studio_admin_accounts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "payments" ADD FOREIGN KEY ("refunded_by_admin_id") REFERENCES "studio_admin_accounts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "payment_logs" ADD FOREIGN KEY ("payment_id") REFERENCES "payments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "payment_logs" ADD FOREIGN KEY ("admin_id") REFERENCES "studio_admin_accounts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "door_lock_codes" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "door_lock_codes" ADD FOREIGN KEY ("studio_id") REFERENCES "studios" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "door_lock_codes" ADD FOREIGN KEY ("manually_sent_by_admin_id") REFERENCES "studio_admin_accounts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "email_logs" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "email_logs" ADD FOREIGN KEY ("customer_account_id") REFERENCES "customer_accounts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "email_templates" ADD FOREIGN KEY ("updated_by_admin_id") REFERENCES "studio_admin_accounts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "bank_accounts" ADD FOREIGN KEY ("studio_id") REFERENCES "studios" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "system_settings" ADD FOREIGN KEY ("updated_by_admin_id") REFERENCES "studio_admin_accounts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "admin_activity_logs" ADD FOREIGN KEY ("admin_id") REFERENCES "studio_admin_accounts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "time_slots" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "special_dates" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "payments" ADD FOREIGN KEY ("bank_account_id") REFERENCES "bank_accounts" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "door_lock_codes" ADD FOREIGN KEY ("email_log_id") REFERENCES "email_logs" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "email_logs" ADD FOREIGN KEY ("email_template_id") REFERENCES "email_templates" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "booking_equipment_items" ADD FOREIGN KEY ("equipment_item_id") REFERENCES "equipment_items" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;
ALTER TABLE "booking_equipment_time_slots" ADD FOREIGN KEY ("equipment_item_id") REFERENCES "equipment_items" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT;

-- AUTO_UPDATE_TIMESTAMP_TRIGGERS


CREATE OR REPLACE FUNCTION "f_auto_update_users_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_users_updated_at"
BEFORE UPDATE ON "users"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_users_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_roles_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_roles_updated_at"
BEFORE UPDATE ON "roles"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_roles_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_user_roles_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_user_roles_updated_at"
BEFORE UPDATE ON "user_roles"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_user_roles_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_customer_accounts_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_customer_accounts_updated_at"
BEFORE UPDATE ON "customer_accounts"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_customer_accounts_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_studio_admin_accounts_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_studio_admin_accounts_updated_at"
BEFORE UPDATE ON "studio_admin_accounts"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_studio_admin_accounts_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_studios_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_studios_updated_at"
BEFORE UPDATE ON "studios"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_studios_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_studio_images_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_studio_images_updated_at"
BEFORE UPDATE ON "studio_images"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_studio_images_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_scenes_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_scenes_updated_at"
BEFORE UPDATE ON "scenes"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_scenes_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_scene_images_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_scene_images_updated_at"
BEFORE UPDATE ON "scene_images"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_scene_images_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_pricing_plans_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_pricing_plans_updated_at"
BEFORE UPDATE ON "pricing_plans"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_pricing_plans_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_business_hours_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_business_hours_updated_at"
BEFORE UPDATE ON "business_hours"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_business_hours_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_time_slots_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_time_slots_updated_at"
BEFORE UPDATE ON "time_slots"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_time_slots_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_special_dates_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_special_dates_updated_at"
BEFORE UPDATE ON "special_dates"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_special_dates_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_bookings_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_bookings_updated_at"
BEFORE UPDATE ON "bookings"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_bookings_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_payments_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_payments_updated_at"
BEFORE UPDATE ON "payments"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_payments_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_door_lock_codes_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_door_lock_codes_updated_at"
BEFORE UPDATE ON "door_lock_codes"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_door_lock_codes_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_email_logs_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_email_logs_updated_at"
BEFORE UPDATE ON "email_logs"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_email_logs_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_email_templates_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_email_templates_updated_at"
BEFORE UPDATE ON "email_templates"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_email_templates_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_bank_accounts_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_bank_accounts_updated_at"
BEFORE UPDATE ON "bank_accounts"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_bank_accounts_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_system_settings_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_system_settings_updated_at"
BEFORE UPDATE ON "system_settings"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_system_settings_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_studio_daily_availability_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_studio_daily_availability_updated_at"
BEFORE UPDATE ON "studio_daily_availability"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_studio_daily_availability_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_scene_prices_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_scene_prices_updated_at"
BEFORE UPDATE ON "scene_prices"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_scene_prices_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_studio_prices_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_studio_prices_updated_at"
BEFORE UPDATE ON "studio_prices"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_studio_prices_updated_at"();


CREATE OR REPLACE FUNCTION "f_auto_update_equipment_items_updated_at"() RETURNS trigger AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "trg_auto_update_equipment_items_updated_at"
BEFORE UPDATE ON "equipment_items"
FOR EACH ROW EXECUTE FUNCTION "f_auto_update_equipment_items_updated_at"();

-- END_AUTO_UPDATE_TIMESTAMP_TRIGGERS
